[tox]
env_list =
    py3{9,10,11,12,13,14,15}
skip_missing_interpreters = true

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    # Based on the version support schedule given here:
    # <https://docs.pytest.org/en/stable/backwards-compatibility.html#python-version-support>
    py39: pytest>=6.2,<8.5
    py3{10,11,12,13,14,15}: pytest>=6.2
    py39: hypothesis>=6,<6.142
    py3{10,11,12,13,14,15}: hypothesis>=6,<6.156

commands =
    pytest --doctest-modules {tty:--color=yes} {posargs}

[testenv:pylint]
description = lint files with Pylint
deps =
    hypothesis>=6,<6.32
    pylint>=2.15
    setuptools
commands =
    pylint {posargs:renumber.py scripts/ setup.py test/}

[testenv:pyright]
description = type check with basedpyright
deps =
    basedpyright
commands =
    basedpyright {posargs:renumber.py scripts/}
